name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        config:
          - {name: "Linux", os: ubuntu-latest, cmake-generator: ""}
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.name }}

    steps:
    - uses: actions/checkout@v2
    - name: Requirements
      shell: bash
      run: |
        sudo apt-get install python3 python3-dev python3-setuptools gcc libtinfo-dev zlib1g-dev build-essential cmake libedit-dev libxml2-dev
        sudo pip3 install numpy decorators attrs
        cd ..
        git clone --recursive https://github.com/apache/tvm.git
        cd tvm
        mkdir build
        cp cmake/config.cmake build
        cd build
        cmake ..
        cmake --build .
        cd ..
        export TVM_HOME=$(pwd)
        export PYTHONPATH=$TVM_HOME/python:${PYTHONPATH}

    - name: Build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Test
      shell: bash
      run: |
        cd examples
        ./run_flow.sh
